package everybody.codes
package y2025

def run(): Unit =
  println("y2025:")
  println("  quest1:")
  println(s"    ├ solution #1: ${timed(Quest1.solve(Quest1.input))}")
  println(s"    ├ solution #2: ${timed(Quest1.solve2(Quest1.input2))}")
  println(s"    └ solution #3: ${timed(Quest1.solve3(Quest1.input3))}")
  println("  quest2:")
  println(s"    ├ solution #1: ${timed(Quest2.solve(Quest2.input))}")
  println(s"    ├ solution #2: ${timed(Quest2.solve2(Quest2.input2))}")
  println(s"    └ solution #3: ${timed(Quest2.solve3(Quest2.input3))}")
  println("  quest3:")
  println(s"    ├ solution #1: ${timed(Quest3.solve(Quest3.input))}")
  println(s"    ├ solution #2: ${timed(Quest3.solve2(Quest3.input2))}")
  println(s"    └ solution #3: ${timed(Quest3.solve3(Quest3.input3))}")
  println("  quest4:")
  println(s"    ├ solution #1: ${timed(Quest4.solve(Quest4.input))}")
  println(s"    ├ solution #2: ${timed(Quest4.solve2(Quest4.input2))}")
  println(s"    └ solution #3: ${timed(Quest4.solve3(Quest4.input3))}")
  println("  quest5:")
  println(s"    ├ solution #1: ${timed(Quest5.solve(Quest5.input))}")
  println(s"    ├ solution #2: ${timed(Quest5.solve2(Quest5.input2))}")
  println(s"    └ solution #3: ${timed(Quest5.solve3(Quest5.input3))}")
  println("  quest6:")
  println(s"    ├ solution #1: ${timed(Quest6.solve(Quest6.input))}")
  println(s"    ├ solution #2: ${timed(Quest6.solve2(Quest6.input2))}")
  println(s"    └ solution #3: ${timed(Quest6.solve3(Quest6.input3))}")
  println("  quest7:")
  println(s"    ├ solution #1: ${timed(Quest7.solve(Quest7.input))}")
  println(s"    └ solution #3: ${timed(Quest7.solve3(Quest7.input3))}")
  println(s"    ├ solution #2: ${timed(Quest7.solve2(Quest7.input2))}")
  // println("  day8:")
  // println(s"    ├ solution #1: ${timed(Day8.solve(Day8.input))}")
  // println(s"    └ solution #2: ${timed(Day8.solve2(Day8.input))}")
  // println("  day9:")
  // println(s"    ├ solution #1: ${timed(Day9.solve(Day9.input))}")
  // println(s"    └ solution #2: ${timed(Day9.solve2(Day9.input))}")
  // println("  day10:")
  // println(s"    ├ solution #1: ${timed(Day10.solve(Day10.input))}")
  // println(s"    └ solution #2: ${timed(Day10.solve2(Day10.input))}")
  // println("  day11:")
  // println(s"    ├ solution #1: ${timed(Day11.solve(Day11.input))}")
  // println(s"    └ solution #2: ${timed(Day11.solve2(Day11.input))}")
  // println("  day12:")
  // println(s"    ├ solution #1: ${timed(Day12.solve(Day12.input))}")
  // println(s"    └ solution #2: ${timed(Day12.solve2(Day12.input))}")
  // println("  day13:")
  // println(s"    ├ solution #1: ${timed(Day13.solve(Day13.input))}")
  // println(s"    └ solution #2: ${timed(Day13.solve2(Day13.input))}")
  // println("  day14:")
  // println(s"    ├ solution #1: ${timed(Day14.solve(Day14.input))}")
  // println(s"    └ solution #2: ${timed(Day14.solve2(Day14.input))}")
  // println("  day15:")
  // println(s"    ├ solution #1: ${timed(Day15.solve(Day15.input))}")
  // println(s"    └ solution #2: ${timed(Day15.solve2(Day15.input))}")
  // println("  day16:")
  // println(s"    ├ solution #1: ${timed(Day16.solve(Day16.input))}")
  // println(s"    └ solution #2: ${timed(Day16.solve2(Day16.input))}")
  // println("  day17:")
  // println(s"    ├ solution #1: ${timed(Day17.solve(Day17.input))}")
  // println(s"    └ solution #2: ${timed(Day17.solve2(Day17.input))}")
  // println("  day18:")
  // println(s"    ├ solution #1: ${timed(Day18.solve(Day18.input))}")
  // println(s"    └ solution #2: ${timed(Day18.solve2(Day18.input))}")
  // println("  day19:")
  // println(s"    ├ solution #1: ${timed(Day19.solve(Day19.input))}")
  // println(s"    └ solution #2: ${timed(Day19.solve2(Day19.input))}")
  // println("  day20:")
  // println(s"    ├ solution #1: ${timed(Day20.solve(Day20.input))}")
  // println(s"    └ solution #2: ${timed(Day20.solve2(Day20.input))}")
